services:
  sqlserver:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: csdl-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
